.. _quickstart:
Quickstart
----------

The easiest thing to see wahts going on is to follow `this YouTube video <https://www.youtube.com/watch?v=YHSXszaFTiM&t=6s>`_ to get the minimum necessary introduction to `PyAero <index.html>`_.


The steps for mesh generation in `PyAero<index.html>`_ can be explained as follows:

1. Load an airfoil contour file
2. Spline and refine the airfoil contour
3. Mesh the refined airfoil contour
4. Export the mesh in the required format

