Loading Airfoils
----------------

Loading airfoils can be done in different ways:

 1. Load one or more airfoil(s) via the *File/Open* menu
 2. Load one or more airfoil(s) via the :ref:`figure_toolbar_open` in the *Toolbar*
 3. Load a predefined airfoil using :ref:`figure_toolbar_open_predefined`
 4. Load one or more airfoil(s) via the inline file browser :ref:`figure_toolbox_area`

.. _figure_menu_open:
.. figure::  images/menu_open.png
   :align:   center
   :target:  _images/menu_open.png
   :name: MenuOpen

   *Open* menu to load an airfoil contour via the file browser

.. _figure_toolbar_open:
.. figure::  images/toolbar_open.png
   :align:   center
   :target:  _images/toolbar_open.png
   :name: Toolbar_Open

   Toolbar icon to load an airfoil contour via the file browser

.. _figure_toolbar_open_predefined:
.. figure::  images/toolbar_open_predefined.png
   :align:   center
   :target:  _images/toolbar_open_predefined.png
   :name: Toolbar_Open

   Toolbar icon to load a predefined airfoil contour

.. seealso:: See tutorial :ref:`tutorial_settings` on how to change the default airfoil.

.. _figure_toolbox_area:
.. figure::  images/toolbox_area.png
   :align:   center
   :target:  _images/toolbox_area.png
   :name: Toolbar_Open

   File browser integrated in the *Toolbar*
