Loading Airfoils
----------------

Loading airfoils is done in three different ways:
 1. Load an airfoil via the *File/Open* menu or the toolbar *Open* icon
 2. Load an airfoil via a airfoil database browser from the Toolbox
 3. Load a predefined airfoil using 1 click

.. figure::  images/menu_open.png
   :align:   center
   :target:  _images/menu_open.png
   :name: MenuOpen

   *Open* menu to load airfoil contour data

.. figure::  images/toolbar_open.png
   :align:   center
   :target:  _images/toolbar_open.png
   :name: Toolbar_Open

   Toolbar icon to load airfoil contour data

.. figure::  images/toolbar_open.png
   :align:   center
   :target:  _images/toolbar_open.png
   :name: Toolbar_Open

   Toolbar icon to load airfoil contour data

