Trailing Edge
-------------

As outlined in the section before, the meshing process relies on the point distribution on the airfoil contour. Real airfoils, i.e. airfoils which are built as a hardware, have a blunt trailing edge. This is due to manufacturing and/or structural reasons. To be able to model this, `PyAero <index.html>`_ has a dedicated function. The following figure shows the change between a sharp trailing edge and a blunt trailing edge.

.. _figure_TE1_animated:
.. figure::  images/TE1_animated.gif
   :align:   center
   :target:  _images/TE1_animated.gif
   :name: TE1_animated
